// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhcm7eZDzHWw3xP1KpsImiSKAwK2OJLhs',
    appId: '1:493144528853:android:612f3a030173e26b008f5c',
    messagingSenderId: '493144528853',
    projectId: 'hostelway-fad58',
    databaseURL: 'https://hostelway-fad58-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hostelway-fad58.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEXNgg7IbR3pjeWvNviY5Z9Lj4smiGivQ',
    appId: '1:493144528853:ios:83e8ffea5ab81f42008f5c',
    messagingSenderId: '493144528853',
    projectId: 'hostelway-fad58',
    databaseURL: 'https://hostelway-fad58-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hostelway-fad58.appspot.com',
    androidClientId: '493144528853-c8s6lfk3q1nmlrf3ie4cc05od5c4ta8i.apps.googleusercontent.com',
    iosBundleId: 'com.example.hostelway',
  );
}
